### ISSUE TITLE
Rerun of completed tasks with missing output

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#1017]
A seeming simple scenario: Run a script with task, task completed. Remove output files, re-run, and sos will find that task already completed. In this case,

1. `sos run -s default` will still check signature and reaches the `task` statement because of signature mismatch.
2. underlying `sos execute task -s default` will refuse to run a completed task.
3. `sos run -s force` will rerun the step and task, but innocent steps/tasks will also be rerun.

This is a new problem with the new task format because previously sos has a `signature-mismatch` status for tasks. That is to say, when we check if a task is completed, it will check if the signature matches, so `sos execute task -s default` will execute if the signature mismatch.

Now, before we restore this `signature-mismatch` status, we need to think what this status means.

This status essentially binds the `task` file with its outputs, so a task would be considered failed whenever the input or output files are moved or removed. Considering you have a large number of jobs on the cluster, it is almost inevitable that input output files will be moved around after jobs are completed. 

There are also technical difficulties in getting this status. Because input and output files are stored outside of task files. We will have to read a task file, get its signature, and check input output files, potentially even calculate md5 of all these files. Considering doing this for ten thousand jobs that you have done in the past month each time you check the status of jobs? We can of course cache the status but we still need to check a lot of files to at least see if their timestamp has been change between each `sos status` check.

Now related to #1015 if we are re-executing a step with lots of jobs, jobs with now removed output files will be rerun, which is not acceptable in many cases.

So we are somehow stuck here with #1015...

**Comment by gaow** [comment]
Oops this is not good ...

>  jobs with now removed output files will be rerun, which is not acceptable in many cases.

why is it not acceptable? It is conceptually clear that pipeline should rerun if output files are gone. We do provide zap feature to remove large files though. I would find task  + output file the duo layer concept to determine job status confusing, unless completely necessary. Also this will do require keeping relevant `*.task` files at all times which can be impractical for large projects on machiens with file number limits.

Other than that, I wonder why do we have to check this? Can we ignore task status check, only check output signature, and create new tasks if output check failed?

**Comment by BoPeng** [comment]
I’m short, people can repeatedly run scripts. For steps without signature, it is arguable if you want to rerun tasks each time. For scripts with signatures, the tasks might be already running but not completed and you do not want to interrupt running tasks.

**Comment by gaow** [comment]
Both are solid points, but in my view it seems to bring more confusion to users than its benefits.

**Comment by BoPeng** [comment]
The behavior has been changed to always execute upon re-execution with signature `default`.

**Comment by gaow** [comment]
Okay but I've now got a number of "ERROR" messages after updating to the current matser and rerun an old project:

```
ERROR: Execute substep b_fit_dap with signature af29cecbfb7375fb
ERROR: Execute substep a_fit_susie10 with signature eac1a9963d53de52
ERROR: Execute substep fit_dap with signature 4c28adbdab5b3ac9
ERROR: Execute substep fit_dap with signature 2134707921053924
ERROR: Execute substep fit_dap with signature c1bc16a9cb06ac4e
ERROR: Execute substep fit_dap with signature c8d6cd58afe04d62
ERROR: Execute substep fit_dap with signature 940e4a1d32257118
ERROR: Execute substep fit_dap with signature c53018064e3f9181
INFO: M2_db0d470cd00a4d77 re-execute completed
ERROR: Execute substep fit_dap with signature f90c6932da3c9444
ERROR: Execute substep fit_dap with signature 51fe703e87
```

should I remove `~/.sos` and `.sos` , or remove existing `*.task` files? Why is this `ERROR` -- reads more like INFO to me?

**Comment by BoPeng** [comment]
I do not understand, I thought that I was reverting a patch (https://github.com/vatlab/SoS/commit/ea40c890d9e5e64495c698f1e99746661a58efe9) but I was adding some test code. I should stop committing at 1am. :-(

**Comment by BoPeng** [comment]
Should have been removed.

**Comment by gaow** [comment]
Okay, but when I check `sos status JOB_ID -v4` I also got this line:

```
WARNING: Failed to decode shell: Compressed data ended before the end-of-stream marker was reached
```

I now see stdout and stderr, but not the actual job script used #1016 .

**Comment by BoPeng** [comment]
Are these new tasks? The warning was caused a version of sos that failed to updated the content of task file properly (a new task failed to clear existing stderr). I have fixed this bug the task file remains corrupted and gives warning like this. These files do not embed .sh file.

I just found and fixed another bug related to embedded `.sh` file. Please update and try again.

**Comment by gaow** [comment]
> Are these new tasks?

Yes i submitted them 30min ago. 

I just updated again but i'll try to test it tmr -- hopefully by them my current batch will be done.

**Comment by BoPeng** [comment]
Then this should be another bug... You can send me the task file to check.

**Comment by gaow** [comment]
ahh oops just purged all task files and trying to run on an updated version ... I'll report back here if I still see it at the end of the run. I hope this is a problem of me not running the updated SoS, not another bug.

**Comment by BoPeng** [comment]
ok. Thanks for your patience. Hopefully sos will be more and more robust with the addition of more and more tests.

**Comment by gaow** [comment]
No thanks for your hard work! I am more than happy to run and report back. Sorry I am sometimes deleting too fast and always try fresh production runs instead of using MWE ... the feedback takes longer.

**Comment by gaow** [comment]
All my production runs are done. The warning no longer shows in the `task` file so it is perhaps due to my out-dated SoS in my previous run. The scripts are now also included. But I do now get a (unwanted?) `trace` message with `-v4`:

```
TRACE: Set CONFIG to {'user_name': 'gaow'} of type <class 'dict'>
```

I guess it is not in the `task` file but merely an artifact running `-v4`.

**Comment by BoPeng** [comment]
Yes, `-v4` should not be set globally if it is intended to show status of tasks. Let me check.

**Comment by gaow** [comment]
I forgot which ticket keeps track of the problem with slow signature check but now I report that signature check is a lot faster in the current version!

Perhaps the only headache now is the database lock? I believe improvements are made. I guess I can report back when I see them again, with relevant output files attached.

**Comment by BoPeng** [comment]
The new version consolidates signatures in bigger packs so that they can be read altogether in much fewer database transactions, which significantly reduces database traffic. It also applies the "check time size before md5" strategy to step signature (in addition to target signature), which should make signature checking much faster as well.

**Comment by BoPeng** [comment]
But I am wondering if concurrent signature checking is still urgent. Right now steps are checked and executed concurrently (if `concurrent=True`) but not if tasks are involved. The idea is that tasks can only be submitted from the master process and steps involving tasks usually do not have anything between `output` and `task`, so running 

```
input: concurrent=True
task:
```
basically starts a bunch of processes and does nothing. Checking existing signature is about the only thing that is useful in subprocesses.

**Comment by BoPeng** [comment]
The issue has been resolved. New discussions should happen in a new ticket.
