### ISSUE TITLE
zmq too many open file error

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1208]
This might be hard to reproduce, but I got this error:

```
Process SoS_Worker-101:
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos/workers.py", line 85, in run
    env.master_socket = env.zmq_context.socket(zmq.PAIR)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/zmq/sugar/context.py", line 146, in socket
    s = self._socket_class(self, socket_type, **kwargs)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/zmq/sugar/socket.py", line 59, in __init__
    super(Socket, self).__init__(*a, **kw)
  File "zmq/backend/cython/socket.pyx", line 328, in zmq.backend.cython.socket.Socket.__init__
zmq.error.ZMQError: Too many open files
```

I'm trying to run a pipe;ine involving many substeps on a single computer with 40 parallel processes. There is [this discussion](https://stackoverflow.com/questions/31220483/zeromq-and-python-multiprocessing-too-many-open-files) on it. Looks like there is some hard default limit that might cause problems for such large scale computations?

**Comment by gaow** [comment]
BTW this one worker's failure did not stop the workflow though. The workflow is still running.

**Comment by BoPeng** [comment]
Yes each worker uses multiple sockets to connect to the master and substep workers etc, and I think the file-locking mechanism also contributed to this.

I am considering removing the file locking stuff.. It prevents one thing, namely two sos instances writing to the same output file, but at a high cost (this and #1183).

**Comment by gaow** [comment]
My job above did not fail, but it did not finish either. It simply hangs after certain point. I killed it and used `-s build` to resume. This round I cannot reproduce the issue. 

> namely two sos instances writing to the same output file

and also on `.task` files?

> I am considering removing the file locking stuff

In a workflow we do check if outputs of different steps overlap? So different instances writing to the same output file only happens when one tries to run multiple `sos` commands over the same set of output? If we can check for overlapping output from parsing the workflow, then I think file locks do not help much thus can be removed.

**Comment by BoPeng** [comment]
> also on `.task` files?

There is a real risk of multiple process writing to `.task` files. For example, a task worker is writing result to `.task` file while the master process is re-submitting it. The locks are not efficient but at least it is released as soon as the task files are updated. The substep lock is problematic because it stays as long as the substep is running, so use much more system resource in terms of file handler.

> a workflow we do check if outputs of different steps overlap?

Yes.

> only happens when one tries to run multiple `sos` commands over the same set of output

Yes but there is also a chance that different workers of the same `sos` instance write to the same output if the (poorly written) sos script has two steps generating overlapping outputs. SoS does not detect this in advance.

I think a proper way to see what is going on is to develop a script with file locks and large number of processes after setting `ulimit` to a smaller number.

**Comment by BoPeng** [comment]
Here is a simple test script

```
[1]
input: for_each = dict(i=range(100))
output: f'A_{i}.txt'

import time
time.sleep(600)
_output.touch()


[2]
input: for_each = dict(i=range(100))
output: f'B_{i}.txt'

import time
time.sleep(600)
_output.touch()

```
Running it with command

```
sos run test -j 40
```
creates 41 processes, mostly substep worker executing the simple `sleep` statement.

Then, one of them has 359 opened file handlers
```
$ lsof -p 4183  | wc -l
359
```

Of which, 167 looks like zmq sockets

```
ZMQbg/5 4183 bpeng1  221u     IPv4  45423      0t0     TCP localhost:34038->localhost:35837 (ESTABLISHED)
```
124 like
```
ZMQbg/5 4183 bpeng1  mem       REG    8,1    14608 2888609 /lib/x86_64-linux-gnu/libdl-2.23.so

```
28 looks like
```
ZMQbg/5 4183 bpeng1  219u  a_inode   0,11        0   11780 [eventfd]
```
25 like
```
ZMQbg/5 4183 bpeng1  200r     FIFO   0,10      0t0   45420 pipe
```
Not saying 6 is a small number but only 6 looks like regular file lock stuff
```
ZMQbg/5 4183 bpeng1    1u      CHR  136,0      0t0       3 /dev/pts/0

```

Summary from another process is

```
$ lsof -p 5028 | tr -s ' ' | cut -f5 -d' ' | sort | uniq -c
     34 a_inode
      6 CHR
      2 DIR
     20 FIFO
    120 IPv4
    124 REG
      1 TYPE
```

**Comment by BoPeng** [comment]
One problem mentioned in another post is that zmq does not free fd instantly so if a large number of sockets are created and destroyed, many of them would stay and cause trouble.

**Comment by gaow** [comment]
Not sure if it is related but when I run it on the cluster, I got:

```
ERROR: Socket operation on non-socket
```

For the time being I am trying to get by with repeatedly using `-s build`.

**Comment by BoPeng** [comment]
With the following script to get all open files and the above script

```
import psutil

def get_open_files():
    procs = {}
    for proc in psutil.process_iter():
        cmd = ' '.join(proc.cmdline())
        if 'sos run' in cmd:
            procs[proc] = {}
            procs[proc]['open_files'] = [x.fd for x in proc.open_files()]
            procs[proc]['open_connections'] = [x.fd for x in proc.connections()]
    return procs

if __name__ == '__main__':
    fds = get_open_files()
    print(f'{len(fds)} processes')
    all_open_files = set()
    all_open_connections = set()
    for proc, ofs in fds.items():
        print(f'{proc.pid} has {len(ofs["open_files"])} open files and {len(ofs["open_connections"])} open connections')
        all_open_files |= set(ofs["open_files"])
        all_open_connections |= set(ofs["open_connections"])
    print(f'Overall {len(all_open_files)} open files and {len(all_open_connections)} open connections')
```

I get for `-j4`
```
$ python procs.py
5 processes
10439 has 2 open files and 41 open connections
10450 has 1 open files and 27 open connections
10453 has 2 open files and 30 open connections
10456 has 2 open files and 30 open connections
10459 has 2 open files and 30 open connections
Overall 5 open files and 43 open connections

```

for `-j10`

```
$ python procs.py
11 processes
8224 has 1 open files and 77 open connections
8233 has 1 open files and 33 open connections
8236 has 2 open files and 30 open connections
8239 has 2 open files and 31 open connections
8242 has 2 open files and 31 open connections
8245 has 2 open files and 31 open connections
8248 has 2 open files and 31 open connections
8249 has 2 open files and 31 open connections
8252 has 2 open files and 31 open connections
8255 has 2 open files and 31 open connections
8258 has 2 open files and 52 open connections
Overall 10 open files and 81 open connections
```
and `-j40`,

```
$ python procs.py
41 processes
11467 has 1 open files and 257 open connections
11476 has 1 open files and 63 open connections
11479 has 2 open files and 30 open connections
11482 has 2 open files and 30 open connections
11483 has 2 open files and 30 open connections
11486 has 2 open files and 30 open connections
11491 has 2 open files and 30 open connections
11494 has 2 open files and 30 open connections
11496 has 2 open files and 30 open connections
11499 has 2 open files and 30 open connections
11501 has 2 open files and 42 open connections
11504 has 2 open files and 42 open connections
11505 has 2 open files and 57 open connections
11512 has 2 open files and 90 open connections
11514 has 2 open files and 96 open connections
11517 has 2 open files and 96 open connections
11519 has 2 open files and 102 open connections
11521 has 2 open files and 102 open connections
11524 has 2 open files and 102 open connections
11529 has 2 open files and 108 open connections
11533 has 2 open files and 125 open connections
11534 has 2 open files and 138 open connections
11539 has 2 open files and 138 open connections
11542 has 2 open files and 150 open connections
11545 has 2 open files and 156 open connections
11548 has 2 open files and 162 open connections
11549 has 2 open files and 162 open connections
11554 has 2 open files and 168 open connections
11557 has 2 open files and 180 open connections
11560 has 2 open files and 186 open connections
11563 has 2 open files and 192 open connections
11564 has 2 open files and 198 open connections
11569 has 2 open files and 198 open connections
11571 has 2 open files and 199 open connections
11574 has 2 open files and 199 open connections
11578 has 2 open files and 203 open connections
11581 has 2 open files and 228 open connections
11584 has 2 open files and 229 open connections
11587 has 2 open files and 240 open connections
11590 has 2 open files and 252 open connections
11593 has 2 open files and 252 open connections
Overall 35 open files and 290 open connections

```

**Comment by BoPeng** [comment]
The conclusion is that file locking contributes one open file per number of worker/process and should not be a big problem. A bigger problem is with zmq because we use separate sockes for different purposes. If we are to reduce the number of sockets used, we will have to combine multiple sockets into fewer multi-purpose ones, which might involve more complex zmq patterns.

@gaow I suppose a good starting point is for you to apply the script to check the number of open files when your workflows are running.

**Comment by gaow** [comment]
Great thanks @BoPeng I'll try it after 7pm this evening and report back here. I suppose it is good idea to reduce the number of sockets used regardless, though.

**Comment by BoPeng** [comment]
The existing sockets work more or less like pipes that were used before. There are certainly room for improvements here but using more complex zmq patterns means more complex communications and potentially more bugs...

But as I said let us first learn the scale of the problem.

**Comment by gaow** [comment]
I it is getting there:

```
[GW] while true; do sleep 20; date; python test.py | tail -1; done
...
Tue Feb  5 20:31:31 CST 2019
Overall 108 open files and 799 open connections
Tue Feb  5 20:32:04 CST 2019
Overall 120 open files and 964 open connections
Tue Feb  5 20:32:47 CST 2019
Overall 112 open files and 1415 open connections
Tue Feb  5 20:33:44 CST 2019
Overall 112 open files and 1415 open connections
Tue Feb  5 20:34:39 CST 2019
Overall 112 open files and 1415 open connections


```

So number of files does not seem to be a problem. It is the connections that keeps increasing. It looks like it does not let go some of the old workers? It is currently stable at 1415 connections > 1024. One thing I immediately notice is that it seems SoS does not let go existing connections. Because I know some steps should be done already, the old process should not be around. But I still see it in the result running that python script.

**Comment by BoPeng** [comment]
So the total number of works keep constant after a while, right? Then the increasing number of connections might be caused by [this problem](https://github.com/zeromq/cppzmq/issues/257), namely zmq does not release sockets immediately.

**Comment by BoPeng** [comment]
This might be related to a hibernating behavior, namely SoS will keep workers around when they are done until new tasks are assigned to them. That is to say, if the script uses all 40 workers and then only uses 20 of them later, the opened sockets for the rest of the 20 workers will still be there.

This does not explain the increasing number of sockets though.

**Comment by gaow** [comment]
> So the total number of works keep constant after a while, right?

you see in the above it starts at 461 open connections, increase to 1415 because it moved on to the next step where there are more substeps, and it stays at 1415. Since it is some computation in production it will take a while to finish it on the desktop, but there will be another step that has exactly the same substeps as the current step. I'd expect the number increase to way over 1415 when we hit that step.

> Then the increasing number of connections might be caused by [this problem](https://github.com/zeromq/cppzmq/issues/257), namely zmq does not release sockets immediately.

Well "immediately" is an understatement. It seems it does not release it at all. See my current status -- you see it starts with 6759, which now has the most connection; some others, eg 6842, have exactly the same status as it was from half hour ago. Looks like a sign of "hibernation"? 

```
[GW] python test.py 
163 processes
6759 has 2 open files and 1155 open connections
6842 has 1 open files and 26 open connections
6845 has 1 open files and 33 open connections
6849 has 1 open files and 40 open connections
6852 has 1 open files and 47 open connections
6855 has 1 open files and 55 open connections
6858 has 1 open files and 63 open connections
6861 has 4 open files and 70 open connections
6865 has 4 open files and 70 open connections
6868 has 4 open files and 76 open connections
6871 has 4 open files and 82 open connections
6874 has 4 open files and 88 open connections
6877 has 4 open files and 94 open connections
6880 has 4 open files and 100 open connections
6883 has 4 open files and 106 open connections
6886 has 4 open files and 112 open connections
6889 has 4 open files and 118 open connections
6892 has 4 open files and 124 open connections
6895 has 4 open files and 130 open connections
6898 has 4 open files and 136 open connections
6901 has 4 open files and 142 open connections
6904 has 4 open files and 148 open connections
6907 has 4 open files and 154 open connections
6910 has 4 open files and 166 open connections
6913 has 4 open files and 166 open connections
6916 has 4 open files and 172 open connections
6919 has 4 open files and 178 open connections
6922 has 4 open files and 184 open connections
6925 has 4 open files and 190 open connections
6928 has 4 open files and 196 open connections
6931 has 4 open files and 202 open connections
6934 has 4 open files and 208 open connections
6937 has 4 open files and 214 open connections
6940 has 4 open files and 220 open connections
6943 has 4 open files and 226 open connections
6946 has 4 open files and 232 open connections
6949 has 4 open files and 238 open connections
6952 has 4 open files and 244 open connections
6955 has 4 open files and 250 open connections
6958 has 4 open files and 256 open connections
6961 has 4 open files and 262 open connections
6964 has 4 open files and 268 open connections
6967 has 4 open files and 274 open connections
6970 has 4 open files and 280 open connections
6973 has 4 open files and 286 open connections
8572 has 1 open files and 296 open connections
8575 has 1 open files and 303 open connections
8578 has 1 open files and 310 open connections
8581 has 1 open files and 318 open connections
8584 has 1 open files and 326 open connections
8587 has 1 open files and 333 open connections
8628 has 1 open files and 340 open connections
8631 has 1 open files and 347 open connections
8634 has 1 open files and 354 open connections
8637 has 1 open files and 361 open connections
8640 has 1 open files and 369 open connections
8643 has 1 open files and 378 open connections
8646 has 1 open files and 385 open connections
8649 has 1 open files and 393 open connections
8652 has 1 open files and 401 open connections
8802 has 2 open files and 671 open connections
8805 has 2 open files and 678 open connections
8810 has 2 open files and 685 open connections
8814 has 2 open files and 692 open connections
9243 has 2 open files and 701 open connections
9261 has 2 open files and 708 open connections
9265 has 2 open files and 715 open connections
9275 has 2 open files and 722 open connections
9287 has 2 open files and 729 open connections
9308 has 2 open files and 737 open connections
9323 has 2 open files and 744 open connections
9331 has 2 open files and 751 open connections
9338 has 2 open files and 759 open connections
9348 has 2 open files and 767 open connections
9351 has 2 open files and 774 open connections
9355 has 2 open files and 782 open connections
9367 has 2 open files and 790 open connections
9380 has 2 open files and 798 open connections
10126 has 2 open files and 802 open connections
10129 has 2 open files and 809 open connections
10151 has 2 open files and 816 open connections
10154 has 2 open files and 823 open connections
10166 has 2 open files and 830 open connections
10169 has 2 open files and 837 open connections
10172 has 2 open files and 844 open connections
10177 has 2 open files and 851 open connections
10741 has 2 open files and 860 open connections
10750 has 2 open files and 867 open connections
10755 has 2 open files and 874 open connections
10765 has 2 open files and 881 open connections
10769 has 2 open files and 888 open connections
10772 has 2 open files and 895 open connections
10776 has 2 open files and 902 open connections
10780 has 2 open files and 910 open connections
10788 has 2 open files and 918 open connections
10800 has 2 open files and 925 open connections
10814 has 2 open files and 932 open connections
10823 has 2 open files and 939 open connections
10828 has 2 open files and 946 open connections
10834 has 2 open files and 953 open connections
10840 has 2 open files and 960 open connections
10850 has 2 open files and 967 open connections
10854 has 2 open files and 974 open connections
10857 has 2 open files and 982 open connections
10868 has 2 open files and 990 open connections
10872 has 2 open files and 998 open connections
10878 has 2 open files and 1006 open connections
10890 has 2 open files and 1013 open connections
10909 has 2 open files and 1022 open connections
10928 has 2 open files and 1029 open connections
10941 has 2 open files and 1038 open connections
10949 has 2 open files and 1046 open connections
10987 has 2 open files and 1054 open connections
10994 has 2 open files and 1062 open connections
11230 has 2 open files and 1067 open connections
11762 has 2 open files and 1076 open connections
11768 has 2 open files and 1081 open connections
11789 has 2 open files and 1090 open connections
11794 has 2 open files and 1095 open connections
11834 has 2 open files and 1104 open connections
11844 has 2 open files and 1111 open connections
11870 has 2 open files and 1119 open connections
11881 has 2 open files and 1126 open connections
12252 has 2 open files and 1133 open connections
12265 has 2 open files and 1141 open connections
12293 has 2 open files and 1149 open connections
12312 has 2 open files and 1156 open connections
25085 has 1 open files and 407 open connections
25094 has 1 open files and 414 open connections
25099 has 1 open files and 421 open connections
25102 has 1 open files and 428 open connections
25492 has 1 open files and 437 open connections
25504 has 1 open files and 444 open connections
25517 has 1 open files and 451 open connections
25522 has 1 open files and 474 open connections
25528 has 1 open files and 466 open connections
25541 has 1 open files and 473 open connections
25544 has 1 open files and 484 open connections
25551 has 1 open files and 492 open connections
25561 has 1 open files and 496 open connections
25567 has 1 open files and 503 open connections
25572 has 1 open files and 513 open connections
25577 has 1 open files and 521 open connections
25587 has 1 open files and 532 open connections
25605 has 1 open files and 533 open connections
27799 has 1 open files and 539 open connections
27802 has 1 open files and 546 open connections
27805 has 1 open files and 553 open connections
27824 has 1 open files and 560 open connections
28208 has 1 open files and 569 open connections
28214 has 1 open files and 576 open connections
28220 has 1 open files and 583 open connections
28230 has 1 open files and 590 open connections
28235 has 1 open files and 597 open connections
28245 has 1 open files and 605 open connections
28251 has 1 open files and 612 open connections
28257 has 1 open files and 619 open connections
28260 has 1 open files and 627 open connections
28274 has 1 open files and 635 open connections
28287 has 1 open files and 643 open connections
28299 has 1 open files and 650 open connections
28314 has 1 open files and 658 open connections
28342 has 1 open files and 666 open connections
Overall 112 open files and 1415 open connections

```

**Comment by BoPeng** [comment]
The numbers are misleading because when a new process is forked, it inherits all open files from the previous process (but do not use them). The only way to get "new" connections is to use the `spawn` process-forking method... I think I can do that on a test bases because spawn is much slower than fork.

**Comment by gaow** [comment]
Okay it will take a while for the workflow to enter the next step and increase the connections. I"ll leave the office now but keeping it running. Is what I reported previously informative enough to understand the scale of problem?

**Comment by BoPeng** [comment]
Yeah, for now I cannot test the start-new-step behavior because my test script has only one step, but let me investigate more.

**Comment by BoPeng** [comment]
These patches merges some sockets and reduces the new fd from 7 to 4 for substep workers. This might cause some problem in performance because the number of threads that handles different types of messages are reduced, so some messages are not handled as promptly as before. I do not expect this becomes a problem though.

Please test and let me know if you see a significant reduction of open files. If you want to check the number of new file handlers of workers, apply the following to the master

```diff
diff --git a/src/sos/__main__.py b/src/sos/__main__.py
index 0006ee13..cafc8f61 100755
--- a/src/sos/__main__.py
+++ b/src/sos/__main__.py
@@ -280,7 +280,8 @@ def get_run_parser(interactive=False, with_workflow=True, desc_only=False):


 def cmd_run(args, workflow_args):
-    #import multiprocessing as mp
+    import multiprocessing as mp
+    mp.set_start_method('spawn')
     # #562, #558, #493
     #
     # if sys.platform != 'win32':
```
and change the function to

```

def get_open_files():
    procs = {}
    for proc in psutil.process_iter():
        try:
            cmd = ' '.join(proc.cmdline())
        except:
            pass
        if 'sos run' in cmd or 'multiprocess' in cmd:
            procs[proc] = {}
            procs[proc]['open_files'] = [x.fd for x in proc.open_files()]
            procs[proc]['open_connections'] = [x.fd for x in proc.connections()]
    return procs
```

**Comment by gaow** [comment]
The `spawn` patch did not work; the complaint was:

```
ERROR: Detailed message:
context has already been set
```

but i can trust the total number of open connections right? so I tried it without tracking new file handlers, using the same procedure as above,

```
Wed Feb  6 00:08:37 CST 2019
Overall 0 open files and 0 open connections
Wed Feb  6 00:08:57 CST 2019
Overall 1 open files and 10 open connections
Wed Feb  6 00:09:17 CST 2019
Overall 105 open files and 200 open connections
Wed Feb  6 00:09:40 CST 2019
Overall 111 open files and 294 open connections
Overall 111 open files and 295 open connections
Wed Feb  6 00:10:29 CST 2019
Overall 105 open files and 295 open connections
Wed Feb  6 00:10:54 CST 2019
Overall 111 open files and 295 open connections
Wed Feb  6 00:11:18 CST 2019
Overall 125 open files and 317 open connections
Wed Feb  6 00:11:44 CST 2019
Overall 110 open files and 408 open connections
Wed Feb  6 00:12:10 CST 2019
Overall 108 open files and 409 open connections
Wed Feb  6 00:12:36 CST 2019
Overall 111 open files and 409 open connections
...
```

At this step it seems to stabilize at 409 connections compared to previously 495 connections. I'm waiting for it to enter the next step.

**Comment by gaow** [comment]
> Is 924 still in danger zone? 

Unless number of socket has "constant space complexity" at some point, there can always be a problem with large scale workflows involving many steps. For example for a given step, there can easily be hundreds to thousands substeps. If the number of sockets scale with number of substeps we may still have issues.

**Comment by BoPeng** [comment]
The number only relates to number of workers so I am curious about the maximum number of new sockets per worker. The spawn patch was supposed to help but unfortunate needs more work for your example.

**Comment by gaow** [comment]
Okay, not sure if this serves a good MWE -- our favorite "hang_test.txt",

[hang_test.sos.txt](https://github.com/vatlab/SoS/files/2836664/hang_test.sos.txt)

I added to each R script a sleep for 5 seconds. Now if you run the monitor to check every second:

```
while true; do date; sleep 2; python test.py | tail -1; done
```

I get:

```
Overall 0 open files and 0 open connections
Wed Feb  6 08:29:54 CST 2019
Overall 0 open files and 0 open connections
Wed Feb  6 08:29:56 CST 2019
Overall 41 open files and 197 open connections
Wed Feb  6 08:29:59 CST 2019
Overall 41 open files and 197 open connections
Wed Feb  6 08:30:02 CST 2019
Overall 41 open files and 197 open connections
Wed Feb  6 08:30:04 CST 2019
Overall 41 open files and 237 open connections
Wed Feb  6 08:30:06 CST 2019
Overall 41 open files and 237 open connections
Wed Feb  6 08:30:08 CST 2019
Overall 29 open files and 249 open connections
Wed Feb  6 08:30:12 CST 2019
Overall 43 open files and 249 open connections
Wed Feb  6 08:30:14 CST 2019
Overall 43 open files and 252 open connections
Wed Feb  6 08:30:16 CST 2019
Overall 43 open files and 238 open connections
Wed Feb  6 08:30:19 CST 2019
Overall 43 open files and 230 open connections
Wed Feb  6 08:30:21 CST 2019
Overall 41 open files and 231 open connections
Wed Feb  6 08:30:23 CST 2019
Overall 41 open files and 231 open connections
Wed Feb  6 08:30:26 CST 2019
Overall 36 open files and 229 open connections
Wed Feb  6 08:30:28 CST 2019
Overall 10 open files and 226 open connections

```

You see there is an increase here in open connections, but it later dropped. Maybe it is not a good MWE. ... to run it:

```
sos run hang_test.sos.txt -j 40 -q none -s force
```

**Comment by gaow** [comment]
Also I'm afraid the attempt from last night does not work. It has made some of my existing workflows hang ...

**Comment by BoPeng** [comment]
I think the root of the problem is that some sockets were kept unclosed till the process is closed. I will tracing the opening and closing of the sockets.

I can revert the socket-merging code after the sockets are properly closed.

**Comment by BoPeng** [comment]
OK, up till now there is no major operation on how zmq works in sos. I just merged a few sockets and made sure all sockets are closed properly. Please test again.

**Comment by gaow** [comment]
Great thanks! My previously failing small workflow seems to work now. I'll soon test on the one from yeasterday and report back. But before that -- it is merged safely right? Because previous problem was caused by merging sockets; but I think being able to close sockets is good already.

**Comment by BoPeng** [comment]
The merged socket should work fine now.

Overall every new substep, step, and workflow worker should add about 4 open files. This does not sound much because it would mean 5x4=20 for -j5. However, because of #1056 , there can be 10 idle processes waiting for 5 processes to complete, so the number of opened files can be a lot more than 20.

Now, if file handler is really a previous resource (if this problem persist), I can do something like:

```
   close_all_other_sockets
   one_socket_waiting_for_result
   open_all_other_sockets
```
so that the waiting processes can release the sockets while waiting. This is a lot of trouble and does not seem to worth it.

**Comment by gaow** [comment]
Okay, the first stage was at  406 open connections and the 2nd stage is 938 connections. It is basically what i saw last night after that patch that. But it works fine now.

> Overall every new substep, step, and workflow worker should add about 4 open files

Sorry I still do not get how it scales -- linearly by a factor of 4 with something? Is it number of steps, substeps or nested workflows?

**Comment by BoPeng** [comment]
It is about the number of sos processes * 4 (or 5), while the number of sos processes equals -j + pending, and the latter depends on the complexity of workflow (e.g. workflow wait for step, step wait for substep and/or task, substep wait for dependency resolving etc).

**Comment by BoPeng** [comment]
SoS will not shutdown any worker till the end, which make the number of open sockets stay at the peak. For example, in the case of -j2

1. Run A, but it depends on B, and C.
2. A, B, pending, run C because C has to run even if there are already 2 pending processes.
3. A, pending, C hibernate, B running
4. A running, B, C hibernate
5. All done, A, B, C release.

So perhaps it makes sense to kill C at step 3 because A, B already satisfies -j2.

**Comment by gaow** [comment]
> SoS will not shutdown any worker till the end,

I see, this explains. 

> So perhaps it makes sense to kill C at step 3 because A, B already satisfies -j2.

Indeed right? Because C is never ever to be used again and is safe to close.

**Comment by BoPeng** [comment]
> Indeed right? Because C is never ever to be used again and is safe to close.

Not really because if B turns pending and needs a new worker, C will be used. It is relatively cheap under linux to start a new process but it takes very long time under windows so I have tried to keep workers ready.

**Comment by gaow** [comment]
I see, this is the 'peak' you are talking about. 

How about Mac? Truthfully I am not sure if Windows support is that important. But say if  from the DAG we can predict how many additional works are needed and keep shutting the hibernated ones until reaching that limit, if the DAG is static?

**Comment by BoPeng** [comment]
The problem comes with the "peak" number of opened files so whether or not we lower the number of opened files when they are not needed does not really matter.

Anyway, I just submitted a patch to lazy-connect to controller so some simple workers might not need to connect to some of the sockets at all. This should help a bit, but not much.

**Comment by minqiao** [comment]
I was told that my problem might be related to changes here so I'm posting on this issue. I have this error:

```
ERROR: [range2var_annotation_2]: 
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
script_4227036311381207733 in <module>
                  col.names=TRUE, row.names=FALSE, sep="\t", quote=FALSE)
      
----> """, container = 'gaow/atac-gwas', workdir = cwd, stdout = f'{_output:n}.stdout')

FileNotFoundError: 2
[range2var_annotation]: 1 pending step: range2var_annotation_3
```

This is not always reproducible but from now on I will try running with `-v3` and see more detailed error.

**Comment by BoPeng** [comment]
Cannot tell what was going on. `FileNotFoundError` is pretty vague.

**Comment by gaow** [comment]
The fact that it is not reproducible between runs, and that it has the number `2` after `FileNotFoundError`, strikes me as socket problems. Also the pipeline worked in previous versions, so I was suggesting @minqiao to post here. @minqiao would you do us a favor just rerunning it with `-v3` and `-s force` over and over again until you are able to reproduce it, and post all the trace back info here?

**Comment by gaow** [comment]
@BoPeng sorry to bring this up again. I have complained earlier somewhere in the post:

> Also I'm afraid the attempt from last night does not work. It has made some of my existing workflows hang ...

It happens after some sockets were merged, which does not help much anyways and you said:

> I can revert the socket-merging code after the sockets are properly closed.

I wonder if it is reverted? Because recently I get random hangs from time to time on some of my large workflows on cluster. It is not always reproducible and does not happen after quite a while. My colleague, however, has this issue on mac computer quite often (about 30% reproducible) even running locally. Not sure if you've got some large workflows to give it a go? It would be nice if it can be resolved just by revisiting the code and making it more robust?

**Comment by BoPeng** [comment]
It is difficult to debug without a test case.. , so basically the reported issue (too many file handlers) is resolved but sos hangs for large jobs? Does it happen in the middle or at the end? Does it happen with failed steps or with successful executions?

**Comment by BoPeng** [comment]
@gaow I have compared the changes before and after the merge and the only difference I could find (unless something buried deeper) is a setting to close socket without waiting for message to be sent, which I turned off because the waiting behavior seems to be safer. I have now changed the mode to no-waiting which will likely resolve the hanging issue.

**Comment by gaow** [comment]
> It is difficult to debug without a test case.. so basically the reported issue (too many file handlers) is resolved but sos hangs for large jobs?

Yes there is no complain about file handler after the patch, but there is occassional hanging behavior. Sorry I was not able to come up with a reasonable MWE that can reliably reproduce it. The hang happens in the middle. 

Let me try to update it for both our computers and see if it persists!

**Comment by gaow** [comment]
Sorry there seems a bug in your last patch (should be an obvious one?)

```
Traceback (most recent call last):
 File "/scratch/midway2/gaow/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
   self.run()
 File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/workers.py", line 219, in run
   disconnect_controllers(env.zmq_context, now=True)
TypeError: disconnect_controllers() got an unexpected keyword argument 'now'
```

**Comment by gaow** [comment]
Again I understand it is difficult to evaluate without an example, but there is an error message reported by my colleague for the current `master`,

```
INFO: M10_f34f4323412c963f submitted to midway2_head with job id 57578061
Exception ignored in: <function Socket.__del__ at 0x7f310a543ea0>
Traceback (most recent call last):
  File "/home/yuxin/miniconda3/lib/python3.7/site-packages/zmq/sugar/socket.py", line 65, in __del__
    def __del__(self):
  File "/home/yuxin/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 29, in signal_handler
    raise ProcessKilled()
sos.workers.ProcessKilled:
ERROR: [7492fb7e-d425-465a-b61c-b34bda33470d]: [z_uniroot]: Failed to get results for tasks 372de4729582aaf3, a63034d2bcaef1c8, 7bcba74a1a299a68, 4cdc4221edb5cd6d, 4d53aa2a6b64b167, a721ed77ec190b43, 5302460e18a5448a, 85806fb5fe81aefa, 29d94c7e6bd0ee8b, f403f6bbda1f4274
```

What should we do to debug it?

**Comment by BoPeng** [comment]
Literally, the messages reads that the process is killed, so the tasks handled by this process were not returned. The question is who kills the process.

**Comment by gaow** [comment]
> The question is who kills the process.

So this refers to a  [sigterm](https://github.com/vatlab/SoS/blob/master/src/sos/workers.py#L89) which is from outside SoS, and there is not much we can do? Or, we can try to handle it better by letting other processes take over, or at least make a more graceful quit message for it?

**Comment by BoPeng** [comment]
The task monitor process might kill it for some reason (e.g. resource exceeding limit) but in that case there should be a message. The cluster schedule might also do it... ,

Yes in theory the controller can resend tasks but the details can be messy (under what conditions that the tasks should be re-sent, how many times should we retry etc).

So it looks like a trial and error task to figure out why this happens.

**Comment by gaow** [comment]
I agree we might not want to do anything to it for now until we see a pattern. I suspect running on the login node the process can get killed without warnings. Can we start by making the quit behavior more graceful and informative? Otherwise it looks like an SoS bug... I"ll then ask my colleague to work with compute nodes directly and see the outcome.

**Comment by BoPeng** [comment]
Just to explain what is happening here.

1. The task is detected to be failed/canceled.
2. The sos master sends the task status to step worker.
3. The step worker reports that due to the failure of one master task, results of 10 tasks are not returned.

However, since the `M10` job might have just been submitted, sos might be reporting the status of a previously failed job (or something like that), but then it is difficult to explain the `ProcessKilled` exception. Basically you want to improve perhaps 3 (reporting of failed tasks) and I am more concerned on why the task/process was killed.

**Comment by gaow** [comment]
> I am more concerned on why the task/process was killed.

I think there is little we can do if it is for external reasons? I suspect it might be the case because on our cluster in principle computationally intensive processes on login node will be killed without notification; although this is the first time I see it happen for SoS. Or are you suggesting there might be a chance that the killed process was from an internal signal?

**Comment by BoPeng** [comment]
is `midway2_head` process-based and can be killed directly?

**Comment by gaow** [comment]
`midway2_head` is the login node that submits jobs to compute node. There is this statement at cluster login:

```
*******************************************************************************

Resource intensive computation jobs running on login nodes will be killed. Please
submit them to slurm.
```

so I suspect this is what happend ... i'll follow up on the other ticket.

**Comment by BoPeng** [comment]
For whatever reason, I see
```
Process SoS_Worker-1:
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda3/envs/sos/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/bpeng1/sos/sos/src/sos/workers.py", line 116, in run
    disconnect_controllers(env.zmq_context)
  File "/Users/bpeng1/sos/sos/src/sos/controller.py", line 104, in disconnect_controllers
    env.ping_thread.join()
  File "/Users/bpeng1/sos/sos/src/sos/controller.py", line 232, in join
    threading.Thread.join(self, timeout)
  File "/Users/bpeng1/anaconda3/envs/sos/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/Users/bpeng1/anaconda3/envs/sos/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/Users/bpeng1/sos/sos/src/sos/workers.py", line 29, in signal_handler
    raise ProcessKilled()
sos.workers.ProcessKilled
INFO: Workflow default (ID=2fccdd0b22ed4eb1) is executed successfully with 1 completed step, 100 completed substeps and 100 completed tasks.
```
after the following workflow is completely properly.

```
[default]
input: for_each=dict(i=range(100))
task: trunk_size=10
sh: expand=True
sleep {i * 0.01}
```
So this might be relevant.

**Comment by BoPeng** [comment]
I deleted the post because it happens on a branch under development for #1212 . The process killed message occurs when the master exists but the workers do not respond so they are killed forcefully, and I do not know if it was the case for your example.

The bottom line is that I could not reproduce the `ProcessKilled` stuff when I tried to kill my workers with `kill -9`, so it might still be something internal to SoS.

**Comment by gaow** [comment]
> The bottom line is that I could not reproduce the ProcessKilled stuff when I tried to kill my workers with kill -9, so it might still be something internal to SoS.

I see, thanks for the clarification! Then it is worrisome? From `git blame` I see those lines were introduce < 1 month ago. The message I posted yesterday was the first time I saw it (and was from my colleague).

**Comment by BoPeng** [comment]
Those lines were supposed to help clean up but can be too helpful as it might have been triggered on the wrong time... we will see.

**Comment by BoPeng** [comment]
just to report that with the new execution model (#1218 ), I am getting about 75 open connections, up to 99  with `-j 12` for the hang test, so the improve is quite dramatic.
